blank_issues_enabled: false

contact_links:
  - name: StackGuardian Community Slack
    url: https://join.slack.com/t/stackguardian-ol78820/shared_invite/zt-2ksag36j9-OjmXqQmyXudgYrV6FmesIQ
    about: Ask questions and get help from the StackGuardian community.