# Base image: Python with additional tools
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /workspace/tirith

# Install virtualenv for creating isolated environments
RUN pip install virtualenv


RUN apt-get update && apt-get install -y git

# Copy only the files necessary for pip install first to leverage Docker caching
COPY . .

# Expose port if Tirith runs any services
EXPOSE 8000
