#!/usr/bin/env python3
"""
Generate the fixture data the Learn and Playground pages render.

Both pages show real Tirith verdicts rather than hand-written ones. This script
runs the actual engine over the worked examples that ship with `tirith ui`
(`src/tirith/tui/examples/`) and writes the results to
`documentation/src/data/fixtures.json`, which the site imports at build time.

Doing it here rather than in the browser is a deliberate trade. Tirith is
Python; evaluating in the browser means shipping a Python runtime to every
visitor. Precomputing keeps the pages fast and keeps the promise that nothing
a visitor brings is uploaded -- there is no evaluation endpoint to upload to.
The cost is that an edited policy cannot be re-evaluated on the page, and the
Playground says so plainly rather than pretending otherwise.

Regenerate after changing any example, or after a change to the engine that
alters result shape:

    python3 documentation/scripts/generate-fixtures.py

The output is committed, so a docs build never needs Python.
"""

import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(REPO_ROOT, "src"))

from tirith.core.core import start_policy_evaluation_from_dict  # noqa: E402
from tirith.tui.examples import load_examples  # noqa: E402

OUT_PATH = os.path.join(REPO_ROOT, "documentation", "src", "data", "fixtures.json")


def exit_code_for(result):
    """
    Mirror the CLI's --fail-on-error contract, from docs/tirith-usage/exit-codes.md.

    Kept as a small local function rather than imported because the CLI decides
    this while also handling flags and IO; what the page needs is only the
    mapping from a tri-state final_result to the code a pipeline would see.
    """
    if "final_result" not in result:
        return 1, "The policy could not be evaluated at all."
    final = result.get("final_result")
    if final is True:
        return 0, "Every check that ran passed."
    if final is False:
        return 3, "A check ran and failed. With --fail-on-error this stops the job."
    return 1, "Every check was skipped, so the policy evaluated nothing. This is not a pass."


def main():
    payload = {
        "_comment": (
            "Generated by documentation/scripts/generate-fixtures.py. Do not edit by hand. "
            "Every result is the real output of the Tirith engine."
        ),
        "examples": _tui_examples(),
        "pack": _starter_pack(),
    }

    with open(OUT_PATH, "w") as handle:
        json.dump(payload, handle, indent=2, sort_keys=False)
        handle.write("\n")

    print(f"wrote {OUT_PATH}")
    print(f"  examples (bundled with `tirith ui`): {len(payload['examples'])}")
    for entry in payload["examples"]:
        print(f"    {entry['key']:<26} exit={entry['exitCode']}")
    print(f"  pack (examples/ starter policies):   {len(payload['pack'])}")
    for entry in payload["pack"]:
        clean = entry["clean"]["exitCode"] if entry.get("clean") else "-"
        print(f"    {entry['key']:<34} fails={entry['exitCode']} clean={clean}")


def _tui_examples():
    """
    The worked examples bundled with `tirith ui`. Editable in the Playground, and the source the
    Learn lesson is written against.
    """
    examples = load_examples()
    if not examples:
        raise SystemExit("no examples found -- has src/tirith/tui/examples/ moved?")

    out = []
    for example in examples:
        result = start_policy_evaluation_from_dict(example.policy, example.input_document)
        code, meaning = exit_code_for(result)
        out.append(
            {
                "key": example.key,
                "title": example.title,
                "summary": example.summary,
                "about": example.about,
                "policy": example.policy,
                "input": example.input_document,
                "result": result,
                "exitCode": code,
                "exitMeaning": meaning,
            }
        )
    return out


def _starter_pack():
    """
    The starter policy pack in examples/ -- policies meant to be copied into a real repository.

    Each one is evaluated twice, which is the whole point of the pack: against the fixture built
    to trip it, and against a clean plan. A policy only ever seen failing might be firing on
    everything; one only ever seen passing might be matching nothing. Both runs are recorded so
    the site can show either, and so a false positive on the clean plan cannot pass unnoticed.
    """
    policies_dir = os.path.join(REPO_ROOT, "examples", "policies")
    inputs_dir = os.path.join(REPO_ROOT, "examples", "inputs")
    if not os.path.isdir(policies_dir):
        print(f"note: {policies_dir} is absent; the starter pack will be empty")
        return []

    clean_path = os.path.join(inputs_dir, "00-clean-plan.passes.json")
    clean_plan = None
    if os.path.exists(clean_path):
        with open(clean_path) as handle:
            clean_plan = json.load(handle)

    out = []
    for name in sorted(os.listdir(policies_dir)):
        if not name.endswith(".json"):
            continue
        key = name[: -len(".json")]
        with open(os.path.join(policies_dir, name)) as handle:
            policy = json.load(handle)

        fails_path = os.path.join(inputs_dir, f"{key}.fails.json")
        if not os.path.exists(fails_path):
            print(f"note: {key} has no .fails.json fixture; skipping")
            continue
        with open(fails_path) as handle:
            document = json.load(handle)

        meta = policy.get("meta", {})
        provider = meta.get("required_provider", "")
        evaluators = policy.get("evaluators", []) or []
        operations = sorted(
            {
                (e.get("provider_args") or {}).get("operation_type")
                for e in evaluators
                if (e.get("provider_args") or {}).get("operation_type")
            }
        )

        result = start_policy_evaluation_from_dict(policy, document)
        code, meaning = exit_code_for(result)

        entry = {
            "key": key,
            "title": meta.get("name") or key,
            "severity": meta.get("severity"),
            "provider": provider,
            "operations": operations,
            "evaluatorCount": len(evaluators),
            "policy": policy,
            "input": document,
            "result": result,
            "exitCode": code,
            "exitMeaning": meaning,
        }

        # Only plan-reading policies can be run against the shared clean plan; a cost or JSON
        # policy would be evaluated against the wrong document shape and report a meaningless
        # verdict, which is worse than reporting nothing.
        if clean_plan is not None and provider.endswith("terraform_plan"):
            clean_result = start_policy_evaluation_from_dict(policy, clean_plan)
            clean_code, clean_meaning = exit_code_for(clean_result)
            entry["clean"] = {
                "exitCode": clean_code,
                "outcome": "passed" if clean_code == 0 else "not clean",
                "meaning": clean_meaning,
            }

        out.append(entry)
    return out


if __name__ == "__main__":
    main()
