name: Linting

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    name: Black linting
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "."

  isort:
    runs-on: ubuntu-latest
    name: isort linting
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort --check-only .