name: Linting
on:
  push:
  pull_request:
    types: [opened, reopened]
    
jobs:
  black:
    runs-on: ubuntu-latest
    name: Black linting
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "."
