name: Linting
permissions:
  contents: read
on:
  push:
  pull_request:
    
jobs:
  black:
    runs-on: ubuntu-latest
    name: Black linting
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "."
